architectury {
    common(enabled_platforms.split(","))
}

loom {
    mixin {
        defaultRefmapName = "uei-emi-refmap.json"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly project(path: ":common", configuration: "namedElements")
    compileOnlyApi "dev.emi:emi-xplat-mojmap:${emi_version}:api"
    compileOnlyApi "dev.emi:emi-xplat-mojmap:${emi_version}"

    modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-common:${jei_version}"
}
