architectury {
    common(enabled_platforms.split(","))
}

loom {
    mixin {
        defaultRefmapName = "uei-emi-refmap.json"
    }
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly project(path: ":common")

    compileOnlyApi "curse.maven:emi-1544558:${emi_neoforge}"
}
