architectury {
    common(enabled_platforms.split(","))
}

loom {
    mixin {
        defaultRefmapName = "uei-emi-refmap.json"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    compileOnly project(path: ":common", configuration: "namedElements")
//    modCompileOnlyApi "dev.emi:emi-xplat-mojmap:${emi_version}:api"
//    modCompileOnlyApi "dev.emi:emi-xplat-mojmap:${emi_version}"

    // https://github.com/TerraformersMC/ModMenu/issues/1069
    modCompileOnlyApi files("libs/emi-forge-1.1.24+1.20.1.jar")
    modCompileOnlyApi files("libs/emi-forge-1.1.24+1.20.1-api.jar")

    modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-common:${jei_version}"
}
