org.gradle.jvmargs=-Xmx3G

minecraft_version=26.2
enabled_platforms=fabric,neoforge

java_version=25

archives_base_name=UniversalEnchantmentInfo
mod_version=1.1.0
maven_group=io.github.suel_ki

mod_id=uei
mod_name=UniversalEnchantmentInfo
mod_description=A JEI/REI/EMI plugin that displays detailed enchantment information
mod_author=Suel_ki
license=MIT

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.156.0+26.2
fabric_emi_enabled=true
fabric_jei_enabled=true
fabric_rei_enabled=true
modmenu_version=20.0.1

# NeoForge
neoforge_version=26.2.0.40-beta
neoforge_loader_version_range=[2,)
neoforge_version_range=[26.2,)
neoforge_emi_enabled=true
neoforge_jei_enabled=true
neoforge_rei_enabled=true

# EMI
emi_enabled=true
emi_version=1.1.24+26.1.2
emi_neoforge=8382319
emi_fabric=8382316
emi_version_range=[1.1.18,)
emi_version_range_fabric=>=1.1

# JEI
jei_enabled=true
jei_version=30.15.0.115
jei_version_range=[30.15,)
jei_version_range_fabric=>=30.15

# REI
rei_enabled=true
rei_version=26.2.820
rei_version_range=[26.2,)
rei_version_range_fabric=>=26.2
cloth_config_version=26.2.155
architectury_version=21.0.6



