org.gradle.jvmargs=-Xmx3G

minecraft_version=1.20.1
enabled_platforms=fabric,forge
parchment_version=2023.09.03

java_version=17

archives_base_name=UniversalEnchantmentInfo
mod_version=1.1.0
maven_group=io.github.suel_ki

mod_id=uei
mod_name=UniversalEnchantmentInfo
mod_description=A JEI/REI/EMI plugin that displays detailed enchantment information
mod_author=Suel_ki
license=MIT

# Fabric
fabric_loader_version=0.16.14
fabric_api_version=0.92.7+1.20.1
fabric_emi_enabled=true
fabric_jei_enabled=true
fabric_rei_enabled=true
modmenu_version=7.2.2

# Forge
forge_version=1.20.1-47.4.10
forge_loader_version_range=[47,)
forge_version_range=[47,)
forge_emi_enabled=true
forge_jei_enabled=true
forge_rei_enabled=true

# EMI
emi_enabled=true
emi_version=1.1.24+1.20.1
emi_version_range=[1.1.18,)
emi_version_range_fabric=>=1.1

# JEI
jei_enabled=true
jei_version=15.20.0.134
jei_version_range=[15.20.0.0,)
jei_version_range_fabric=>=15.20

# REI
rei_enabled=true
rei_version=12.1.785
rei_version_range=[12.1.705,)
rei_version_range_fabric=>=12.1
cloth_config_version=11.1.136
architectury_version=9.2.14



