architectury {
    common(enabled_platforms.split(","))
}

dependencies {
    compileOnly project(path: ":common", configuration: "namedElements")
    modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    modCompileOnly "mezz.jei:jei-${minecraft_version}-common:${jei_version}"
}
